// @ts-check
/// <reference types="@actions/github-script" />

const fs = require("fs");
const { getMissingInfoSections } = require("./missing_messages_helper.cjs");
const { getBlockedDomains, generateBlockedDomainsSection } = require("./firewall_blocked_domains.cjs");

/**
 * Generates a standalone workflow-id XML comment marker for searchability.
 * This marker enables finding all items (issues, discussions, PRs, comments)
 * generated by a specific workflow.
 *
 * @param {string} workflowId - Workflow identifier
 * @returns {string} Standalone workflow-id XML comment marker
 */
function generateWorkflowIdMarker(workflowId) {
  return `<!-- gh-aw-workflow-id: ${workflowId} -->`;
}

/**
 * Gets the workflow-id marker content (without XML comment wrapper) for searching.
 * This is used when searching for issues/discussions/PRs by workflow-id.
 *
 * @param {string} workflowId - Workflow identifier
 * @returns {string} Workflow-id marker content for search queries
 */
function getWorkflowIdMarkerContent(workflowId) {
  return `gh-aw-workflow-id: ${workflowId}`;
}

/**
 * Generates an XML comment marker with agentic workflow metadata for traceability.
 * This marker enables searching and tracing back items generated by an agentic workflow.
 *
 * Note: This function is duplicated in messages_footer.cjs. While normally we would
 * consolidate to a shared module, importing messages_footer.cjs here would cause the
 * bundler to inline messages_core.cjs which contains 'GH_AW_SAFE_OUTPUT_MESSAGES:' in
 * a warning message, breaking tests that check for env var declarations.
 *
 * @param {string} workflowName - Name of the workflow
 * @param {string} runUrl - URL of the workflow run
 * @returns {string} XML comment marker with workflow metadata
 */
function generateXMLMarker(workflowName, runUrl) {
  // Read engine metadata from environment variables
  const engineId = process.env.GH_AW_ENGINE_ID || "";
  const engineVersion = process.env.GH_AW_ENGINE_VERSION || "";
  const engineModel = process.env.GH_AW_ENGINE_MODEL || "";
  const trackerId = process.env.GH_AW_TRACKER_ID || "";

  // Build the key-value pairs for the marker
  const parts = [];

  // Always include agentic-workflow name
  parts.push(`gh-aw-agentic-workflow: ${workflowName}`);

  // Add tracker-id if available (for searchability and tracing)
  if (trackerId) {
    parts.push(`gh-aw-tracker-id: ${trackerId}`);
  }

  // Add engine ID if available
  if (engineId) {
    parts.push(`engine: ${engineId}`);
  }

  // Add version if available
  if (engineVersion) {
    parts.push(`version: ${engineVersion}`);
  }

  // Add model if available
  if (engineModel) {
    parts.push(`model: ${engineModel}`);
  }

  // Always include run URL
  parts.push(`run: ${runUrl}`);

  // Return the XML comment marker
  return `<!-- ${parts.join(", ")} -->`;
}

/**
 * Generate footer with AI attribution and workflow installation instructions
 * @param {string} workflowName - Name of the workflow
 * @param {string} runUrl - URL of the workflow run
 * @param {string} workflowSource - Source of the workflow (owner/repo/path@ref)
 * @param {string} workflowSourceURL - GitHub URL for the workflow source
 * @param {number|undefined} triggeringIssueNumber - Issue number that triggered this workflow
 * @param {number|undefined} triggeringPRNumber - Pull request number that triggered this workflow
 * @param {number|undefined} triggeringDiscussionNumber - Discussion number that triggered this workflow
 * @returns {string} Footer text
 */
function generateFooter(workflowName, runUrl, workflowSource, workflowSourceURL, triggeringIssueNumber, triggeringPRNumber, triggeringDiscussionNumber) {
  let footer = `\n\n> AI generated by [${workflowName}](${runUrl})`;

  // Add reference to triggering issue/PR/discussion if available
  if (triggeringIssueNumber) {
    footer += ` for #${triggeringIssueNumber}`;
  } else if (triggeringPRNumber) {
    footer += ` for #${triggeringPRNumber}`;
  } else if (triggeringDiscussionNumber) {
    footer += ` for discussion #${triggeringDiscussionNumber}`;
  }

  if (workflowSource && workflowSourceURL) {
    // Load workflow install note template
    const promptsDir = process.env.GH_AW_PROMPTS_DIR || "/opt/gh-aw/prompts";
    const installNoteTemplatePath = `${promptsDir}/workflow_install_note.md`;
    const installNoteTemplate = fs.readFileSync(installNoteTemplatePath, "utf8");
    const installNote = installNoteTemplate.replace("{workflow_source}", workflowSource);
    footer += `\n>\n> ${installNote}`;
  }

  // Add missing tools and data sections if available
  const missingInfoSections = getMissingInfoSections();
  if (missingInfoSections) {
    footer += missingInfoSections;
  }

  // Add firewall blocked domains section if any domains were blocked
  const blockedDomains = getBlockedDomains();
  const blockedDomainsSection = generateBlockedDomainsSection(blockedDomains);
  if (blockedDomainsSection) {
    footer += blockedDomainsSection;
  }

  // Add XML comment marker for traceability
  footer += "\n\n" + generateXMLMarker(workflowName, runUrl);

  footer += "\n";
  return footer;
}

module.exports = {
  generateFooter,
  generateXMLMarker,
  generateWorkflowIdMarker,
  getWorkflowIdMarkerContent,
};
